DEFAULT_KEYWORD_LIST = [
    "Junior developer",
    "Web developer",
    "Technical support specialist",
    "Digital marketer",
    "cyber security engineer",
    "Data analyst",
    "Application developer",
    "Software engineer",
    "Full stack developer",
    "Back end developer",
    "Information security analyst",
    "User experience designer",
    "Help desk support technician",
    "Computer systems analyst",
    "DevOps engineer",
]
DEFAULT_LOCATION_LIST = [
    "Atlanta, GA",
    "Austin, TX",
    "Baltimore",
    "Boston",
    "Chicago",
    "Dallas/Ft. Worth",
    "Denver",
    "Detroit",
    "Los Angles/Orange Co.",
    "Madison",
    "Minneapolis/St. Paul",
    "Montreal",
    "New York Metro",
    "Ottawa",
    "Phoenix, AZ",
    "Portland",
    "Raleigh-Durham",
    "Salt Lake City",
    "San Diego",
    "San Francisco Bay Area",
    "Seattle, WA",
    "Toronto",
    "Vancouver",
    "Washington, D.C.",
    "Waterloo Region",
]
